// Code generated by "stringer -type=ExprTag"; DO NOT EDIT.

package examples

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExprTagNumber-0]
	_ = x[ExprTagAdd-1]
}

const _ExprTag_name = "ExprTagNumberExprTagAdd"

var _ExprTag_index = [...]uint8{0, 13, 23}

func (i ExprTag) String() string {
	if i < 0 || i >= ExprTag(len(_ExprTag_index)-1) {
		return "ExprTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExprTag_name[_ExprTag_index[i]:_ExprTag_index[i+1]]
}
